export const formErrors = {
    required: 'required',
    invalidGitRepoSlug: 'invalidGitRepoSlug',
    invalidGitRepoBranch: 'invalidGitRepoBranch',
    invalidGitRepoRemoteUrl: 'invalidGitRepoRemoteUrl',
    invalidExternalId: 'invalidExternalId',
    invalidFileName: 'invalidFileName',
    invalidHexColor: 'invalidHexColor',
    messageRequiresContentOrFiles: 'messageRequiresContentOrFiles',
    apiKeyExpiryMustBeFuture: 'apiKeyExpiryMustBeFuture',
    activeFlowsLimitMin: 'activeFlowsLimitMin',
    activeFlowsLimitMax: 'activeFlowsLimitMax',
    invalidCloudflareAccountId: 'invalidCloudflareAccountId',
    invalidCloudflareGatewayId: 'invalidCloudflareGatewayId',
    invalidAzureResourceName: 'invalidAzureResourceName',
} as const
